import {describe, it, expect} from 'vitest'
import {converter, wcagContrast} from 'culori'
import {
  COLOUR_DEFAULTS,
  acceptDarkGround,
  acceptLightGround,
  buildColorCSS,
  buildDesignTokenCSS,
  deriveInverseNeutrals,
  deriveNeutrals,
  heroTintOf,
  hexToRgbTriplet,
  mutedOf,
  resolvePalette,
  retoneFill,
  validateWcag,
} from '../designTokens'
import {PALETTE_PRESETS, matchPreset, presetInputs} from '../palettes'

// The colour engine's behaviour, rule by rule. The guarantee over arbitrary input
// is colourGuarantee.test.ts; what existing sites see is pinned there too, against
// the old engine's captured output. The two kinds of assertion do different jobs:
// an invariant computed here catches a broken rule, and the small golden tables
// below catch a CHANGED rule that still passes every invariant (a 0.05 step, a
// 0.06 chroma cap), which would otherwise restyle every client silently
// (WS-V1-PHASE14-DESIGN §7 amendment 15).

const toOklch = converter('oklch')
const oklch = (hex: string) => {
  const c = toOklch(hex)
  return {l: (c?.l as number) ?? 0, c: (c?.c as number) ?? 0, h: (c?.h as number) ?? 0}
}
const ratio = (a: string, b: string) => wcagContrast(a, b) as number

/** Hue difference in OKLab units, which stays meaningful at low chroma where degrees do not. */
function deltaH(a: string, b: string): number {
  const x = oklch(a)
  const y = oklch(b)
  const dh = ((((y.h - x.h) % 360) + 540) % 360) - 180
  return 2 * Math.sqrt(x.c * y.c) * Math.sin((dh * Math.PI) / 360)
}

// ─── The derivation table ─────────────────────────────────────────────────────

describe('the derivation, row by row', () => {
  const t = resolvePalette({}).tokens

  it('the code defaults are the render every built client already has', () => {
    expect(COLOUR_DEFAULTS).toEqual({darkGround: '#141414', lightGround: '#ffffff', accent: '#666666'})
    expect(t['--color-brand-dark']).toBe('#141414')
    expect(t['--color-background']).toBe('#ffffff')
    expect(t['--color-accent']).toBe('#666666')
    expect(t['--color-action']).toBe('#666666')
  })

  it('muted is the light ground at L −0.03 and hero-tint at L −0.015, on the ground’s own hue', () => {
    expect(t['--color-muted']).toBe('#f5f5f5')
    expect(t['--color-hero-tint']).toBe('#fafafa')
    const cream = '#f5eedc'
    expect(oklch(mutedOf(cream)).l).toBeCloseTo(oklch(cream).l - 0.03, 2)
    expect(oklch(heroTintOf(cream)).l).toBeCloseTo(oklch(cream).l - 0.015, 2)
    // A cream ground's steps stay cream, not the grey today's recipe produced.
    expect(Math.abs(deltaH(mutedOf(cream), cream))).toBeLessThan(0.005)
    expect(oklch(heroTintOf(cream)).c).toBeGreaterThan(0.01)
  })

  it('muted and hero-tint carry no accent hue: a red accent leaves every surface exactly as a grey one does', () => {
    const grey = resolvePalette({}).tokens
    const red = resolvePalette({accent: '#a12a2f'}).tokens
    for (const surface of ['--color-background', '--color-muted', '--color-hero-tint', '--color-brand-dark', '--color-scrim']) {
      expect(red[surface], surface).toBe(grey[surface])
    }
  })

  it('accent-text is the accent where it passes, else the accent darkened at a fixed hue', () => {
    const table: Array<[string, string, string]> = [
      // name, accent, accent-text. Generated by the engine at the build and
      // committed: a change here is a visible restyle of every kicker and link.
      ['gold', '#c9a227', '#846700'],
      ['orange', '#f57c00', '#ae5600'],
      ['coral', '#ff6f61', '#c63a31'],
      ['blue', '#1e88e5', '#0070c4'],
      ['red', '#a12a2f', '#a12a2f'],
    ]
    for (const [name, accent, text] of table) {
      const p = resolvePalette({accent}).tokens
      expect(p['--color-accent-text'], name).toBe(text)
      for (const ground of [p['--color-background'], p['--color-hero-tint'], p['--color-muted']]) {
        expect(ratio(text, ground), name).toBeGreaterThanOrEqual(4.5)
      }
      expect(Math.abs(deltaH(accent, text)), `${name} keeps its hue`).toBeLessThan(0.005)
    }
  })

  it('the accent on dark is the accent brightened, and passes on the ground', () => {
    const p = resolvePalette({darkGround: '#14213d', accent: '#c9a227'}).tokens
    expect(p['--color-accent-on-dark']).toBe('#f0d58c')
    expect(ratio(p['--color-accent-on-dark'], p['--color-brand-dark'])).toBeGreaterThanOrEqual(4.5)
  })

  it('action falls back to the accent and keeps the outlined-text rule', () => {
    const p = resolvePalette({accent: '#c9a227'}).tokens
    expect(p['--color-action']).toBe('#c9a227')
    // Gold fails 4.5:1 as outlined text on white, so the text form is brand-dark.
    expect(p['--color-action-text']).toBe(p['--color-brand-dark'])
    const own = resolvePalette({accent: '#c9a227', action: '#14213d'}).tokens
    expect(own['--color-action']).toBe('#14213d')
    expect(own['--color-action-text']).toBe('#14213d')
  })

  it('action text on dark steps lighter at its own hue until it reads (#666666 measured 3.21:1)', () => {
    const p = resolvePalette({}).tokens
    expect(p['--color-action-text-on-dark']).toBe('#838383')
    expect(ratio(p['--color-action-text-on-dark'], p['--color-brand-dark'])).toBeGreaterThanOrEqual(4.5)
    const bright = resolvePalette({action: '#f5a623'}).tokens
    expect(bright['--color-action-text-on-dark']).toBe('#f5a623')
  })

  it('foreground-subtle is darkened only as far as 4.5:1 (#8f8f8f measured 3.23:1 on white)', () => {
    const p = resolvePalette({}).tokens
    expect(p['--color-foreground-subtle']).toBe('#707070')
    expect(p['--color-foreground']).toBe(deriveNeutrals('#141414')['color-foreground-on-light'])
    expect(p['--color-foreground-muted']).toBe(deriveNeutrals('#141414')['color-foreground-muted-on-light'])
  })

  it('the control boundary reaches 3:1 on every light ground, and on dark', () => {
    const p = resolvePalette({}).tokens
    for (const ground of [p['--color-background'], p['--color-hero-tint'], p['--color-muted']]) {
      expect(ratio(p['--color-border-control'], ground)).toBeGreaterThanOrEqual(3)
    }
    expect(ratio(p['--color-border-control-on-dark'], p['--color-brand-dark'])).toBeGreaterThanOrEqual(3)
    // The decorative divider is unchanged.
    expect(p['--color-border']).toBe('#e4e4e4')
  })

  it('a text link’s hover keeps the button hover where it reads, and is the on-dark body text on dark', () => {
    const p = resolvePalette({}).tokens
    expect(p['--color-action-text-hover']).toBe(p['--color-action-hover'])
    expect(p['--color-action-text-hover-on-dark']).toBe(p['--color-foreground-on-dark'])
    // A gold action lightens on hover and would fail as text on white.
    const gold = resolvePalette({accent: '#c9a227'}).tokens
    expect(gold['--color-action-text-hover']).toBe(gold['--color-action-text'])
  })

  it('a selected pill gains a ring only where the action cannot mark the state at 3:1', () => {
    const grey = resolvePalette({}).tokens
    expect(grey['--color-action-state-cue']).toBe('transparent')
    expect(grey['--color-action-state-cue-on-dark']).toBe('transparent')
    const gold = resolvePalette({accent: '#c9a227'}).tokens
    expect(gold['--color-action-state-cue']).toBe(gold['--color-action-text'])
    expect(ratio(gold['--color-action-state-cue'], gold['--color-background'])).toBeGreaterThanOrEqual(3)
  })

  it('the scrim is brand-dark capped at L 0.20', () => {
    expect(resolvePalette({}).tokens['--color-scrim']).toBe('#141414')
    const light = resolvePalette({darkGround: '#36454f'}).tokens
    // 8-bit hex rounding moves OKLCH L by up to about 0.001.
    expect(oklch(light['--color-scrim']).l).toBeLessThanOrEqual(0.201)
    expect(Math.abs(deltaH(light['--color-scrim'], light['--color-brand-dark']))).toBeLessThan(0.005)
  })

  it('every light-island twin is emitted and equals its cascade-aware value at :root', () => {
    for (const inputs of [{}, presetInputs(PALETTE_PRESETS.find((p) => p.id === 'navy-brass')!)]) {
      const p = resolvePalette(inputs).tokens
      for (const name of ['foreground', 'foreground-muted', 'foreground-subtle', 'border', 'border-control', 'accent', 'accent-text', 'action-text', 'ring-focus', 'star-outline']) {
        expect(p[`--color-${name}-on-light`], name).toBe(p[`--color-${name}`])
      }
    }
  })

  it('buildColorCSS emits one :root block of the resolved tokens', () => {
    const css = buildColorCSS({accent: '#a12a2f'})
    expect(css.startsWith(':root{')).toBe(true)
    expect(css).toContain('--color-accent:#a12a2f')
    expect(css).toContain('--color-accent-text:#a12a2f')
    expect(css).toMatch(/--shadow-rgb:\d+ \d+ \d+/)
    expect(css).not.toContain('--role-')
  })

  it('a navy dark ground gives cool-tinted neutrals and a cool shadow', () => {
    const [r, , b] = hexToRgbTriplet(deriveNeutrals('#1e3a8a')['color-foreground-on-light']).split(' ').map(Number)
    expect(b).toBeGreaterThan(r)
  })
})

// ─── Acceptance ───────────────────────────────────────────────────────────────

describe('dark ground acceptance', () => {
  // name, input, accepted, steps. Generated by the engine at the build and
  // committed: the curated hues and four vivid inputs, including a maroon like the
  // one the design record first imagined on the fixture.
  const TABLE: Array<[string, string, string, number]> = [
    ['navy', '#000080', '#0c2257', 0],
    ['deep navy', '#14213d', '#14213d', 0],
    ['charcoal', '#36454f', '#36454f', 0],
    ['black', '#111111', '#111111', 0],
    ['forest', '#228b22', '#1b4f19', 9],
    ['burgundy', '#800020', '#6e272d', 0],
    ['teal', '#008080', '#004e4e', 8],
    ['brand red', '#e53935', '#77312b', 10],
    ['brand green', '#43a047', '#1b521e', 12],
    ['brand blue', '#1e88e5', '#14497a', 11],
    ['maroon', '#8b1e1e', '#742e2a', 1],
  ]

  it('matches the committed table', () => {
    for (const [name, input, hex, steps] of TABLE) {
      const a = acceptDarkGround(input)
      expect([a.hex, a.steps], name).toEqual([hex, steps])
      expect(a.adjusted, name).toBe(hex !== input)
    }
  })

  it('every accepted ground carries white at 7:1 and the lightest dark text tier at 4.5:1', () => {
    for (const [name, input] of TABLE) {
      const a = acceptDarkGround(input)
      expect(ratio('#ffffff', a.hex), name).toBeGreaterThanOrEqual(7)
      expect(ratio(deriveInverseNeutrals(input)['color-foreground-subtle-on-dark'], a.hex), name).toBeGreaterThanOrEqual(4.5)
      // Chroma capped at 0.10, plus 8-bit hex rounding.
      expect(oklch(a.hex).c, name).toBeLessThanOrEqual(0.102)
    }
  })

  it('keeps the input’s hue, and accepting the result again changes nothing', () => {
    for (const [name, input] of TABLE) {
      const a = acceptDarkGround(input)
      expect(Math.abs(deltaH(input, a.hex)), name).toBeLessThan(0.005)
      const again = acceptDarkGround(a.hex)
      expect([again.hex, again.adjusted], name).toEqual([a.hex, false])
    }
  })

  it('the inverse neutrals keep a trace of the ground’s hue and descend in contrast', () => {
    const inv = deriveInverseNeutrals('#821428')
    const ground = acceptDarkGround('#821428').hex
    const bright = ratio(inv['color-foreground-on-dark'], ground)
    const muted = ratio(inv['color-foreground-muted-on-dark'], ground)
    const subtle = ratio(inv['color-foreground-subtle-on-dark'], ground)
    expect(bright).toBeGreaterThan(muted)
    expect(muted).toBeGreaterThan(subtle)
    expect(subtle).toBeGreaterThanOrEqual(4.5)
    for (const v of Object.values(inv)) expect(oklch(v).c).toBeGreaterThan(0)
  })
})

describe('light ground acceptance', () => {
  it('white and every preset’s light ground are accepted unchanged', () => {
    expect(acceptLightGround('#ffffff', '#141414').adjusted).toBe(false)
    for (const p of PALETTE_PRESETS) {
      if (p.lightGround) expect(acceptLightGround(p.lightGround, p.darkGround).adjusted, p.id).toBe(false)
    }
  })

  it('a dark colour typed as the light ground steps up until the text tiers can sit on its muted step', () => {
    const a = acceptLightGround('#14213d', '#14213d')
    expect(a.adjusted).toBe(true)
    const t = resolvePalette({lightGround: '#14213d', darkGround: '#14213d'}).tokens
    expect(t['--color-background']).toBe(a.hex)
    expect(ratio(t['--color-foreground-subtle'], t['--color-muted'])).toBeGreaterThanOrEqual(4.5)
    expect(acceptLightGround(a.hex, '#14213d').adjusted).toBe(false)
  })
})

describe('fill re-tone', () => {
  it('moves a mid-tone brand red one step so its text passes, and leaves a passing fill alone', () => {
    const red = retoneFill('#e53935')
    expect(red.adjusted).toBe(true)
    expect(red.steps).toBe(1)
    expect(ratio('#ffffff', red.hex)).toBeGreaterThanOrEqual(4.5)
    expect(retoneFill('#a12a2f')).toEqual({input: '#a12a2f', hex: '#a12a2f', adjusted: false, steps: 0})
    for (const p of PALETTE_PRESETS) expect(retoneFill(p.accent).adjusted, p.id).toBe(false)
  })
})

// ─── Presets ──────────────────────────────────────────────────────────────────

describe('palette presets', () => {
  it('there are fifteen, with unique ids in the ground-accent form', () => {
    expect(PALETTE_PRESETS).toHaveLength(15)
    expect(new Set(PALETTE_PRESETS.map((p) => p.id)).size).toBe(15)
    for (const p of PALETTE_PRESETS) {
      expect(p.id).toMatch(/^[a-z]+-[a-z]+$/)
      expect(p.provenance.domains.length, p.id).toBeGreaterThan(0)
    }
  })

  it('every preset keeps its accent in text, reads differently from the heading, and needs no adjustment', () => {
    for (const p of PALETTE_PRESETS) {
      const palette = resolvePalette(presetInputs(p))
      const t = palette.tokens
      expect(t['--color-accent-text'], p.id).not.toBe(t['--color-brand-dark'])
      expect(Math.abs(deltaH(p.accent, t['--color-accent-text'])), p.id).toBeLessThan(0.005)
      expect(palette.acceptance.darkGround.adjusted, p.id).toBe(false)
      expect(palette.acceptance.lightGround.adjusted, p.id).toBe(false)
      expect(palette.acceptance.accent.adjusted, p.id).toBe(false)
    }
  })

  it('the active preset is derived from the stored values, and any edit makes it custom', () => {
    const navyBrass = PALETTE_PRESETS.find((p) => p.id === 'navy-brass')!
    expect(matchPreset(presetInputs(navyBrass))?.id).toBe('navy-brass')
    expect(matchPreset({darkGround: '#1C2B4A', lightGround: '#F5EEDC', accent: '#B8893A'})?.id).toBe('navy-brass')
    expect(matchPreset({...presetInputs(navyBrass), accent: '#b8893b'})).toBeNull()
    const blackGold = PALETTE_PRESETS.find((p) => p.id === 'black-gold')!
    expect(matchPreset({darkGround: blackGold.darkGround, lightGround: '#ffffff', accent: blackGold.accent})?.id).toBe('black-gold')
    expect(matchPreset({})).toBeNull()
  })
})

// ─── validateWcag ─────────────────────────────────────────────────────────────

describe('validateWcag', () => {
  it('reports the blocking WCAG pairs and two design warnings, each with its threshold', () => {
    const results = validateWcag(resolvePalette({}))
    const blocking = results.filter((r) => r.blocking)
    expect(blocking.length).toBeGreaterThan(30)
    expect(blocking.every((r) => r.passes)).toBe(true)
    expect(results.find((r) => r.pair === 'foreground-subtle on muted')?.min).toBe(4.5)
    expect(results.find((r) => r.pair === 'border-control on background')?.min).toBe(3)
    expect(results.filter((r) => !r.blocking).map((r) => r.pair)).toEqual([
      'accent on background (graphics beside text)',
      'accent-text against foreground (emphasis distinctness)',
    ])
  })

  it('flags gold as a graphic on white as a warning, never as a failure', () => {
    const results = validateWcag(resolvePalette({accent: '#c9a227'}))
    const graphic = results.find((r) => r.pair.startsWith('accent on background'))!
    expect(graphic.passes).toBe(false)
    expect(graphic.blocking).toBe(false)
  })
})

// ─── Unchanged UI-token and helper behaviour ──────────────────────────────────

describe('hexToRgbTriplet', () => {
  it('returns space-separated R G B integers', () => {
    const result = hexToRgbTriplet('#ffffff')
    expect(result).toBe('255 255 255')
  })

  it('returns "0 0 0" for pure black', () => {
    expect(hexToRgbTriplet('#000000')).toBe('0 0 0')
  })

  it('warm text-dark (#1c1314) returns warm near-black triplet', () => {
    // #1c1314 = rgb(28, 19, 20)
    expect(hexToRgbTriplet('#1c1314')).toBe('28 19 20')
  })

  it('result format matches /^\\d+ \\d+ \\d+$/', () => {
    const textDark = deriveNeutrals('#821428')['color-foreground-on-light']
    expect(hexToRgbTriplet(textDark)).toMatch(/^\d+ \d+ \d+$/)
  })

  it('returns "0 0 0" for invalid input', () => {
    expect(hexToRgbTriplet('not-a-color')).toBe('0 0 0')
  })
})

// ─── --shadow-rgb in buildColorCSS ───────────────────────────────────────────

describe('buildDesignTokenCSS elevation tokens', () => {
  it('level 0 (default) outputs --shadow-card-rest:none', () => {
    const css = buildDesignTokenCSS()
    expect(css).toContain('--shadow-card-rest:none')
    expect(css).toContain('--shadow-card-hover:none')
    expect(css).toContain('--transform-card-hover:0px')
  })

  it('elevationStyle "0" outputs none explicitly', () => {
    const css = buildDesignTokenCSS(undefined, undefined, undefined, '0')
    expect(css).toContain('--shadow-card-rest:none')
  })

  it('level 1 outputs 2-layer shadow for rest', () => {
    const css = buildDesignTokenCSS(undefined, undefined, undefined, '1')
    const match = css.match(/--shadow-card-rest:([^;}]+)/)
    const layers = (match?.[1] ?? '').split('rgb(').length - 1
    expect(layers).toBe(2)
  })

  it('level 4 outputs 3-layer shadow for rest', () => {
    const css = buildDesignTokenCSS(undefined, undefined, undefined, '4')
    const match = css.match(/--shadow-card-rest:([^;}]+)/)
    const layers = (match?.[1] ?? '').split('rgb(').length - 1
    expect(layers).toBe(3)
  })

  it('level 6 outputs 3-layer shadow with largest offsets', () => {
    const css = buildDesignTokenCSS(undefined, undefined, undefined, '6')
    expect(css).toContain('48px')
    expect(css).toContain('64px')
    expect(css).toContain('--transform-card-hover:-3px')
  })

  it('transform-card-hover values increase with intensity', () => {
    const level2 = buildDesignTokenCSS(undefined, undefined, undefined, '2')
    const level4 = buildDesignTokenCSS(undefined, undefined, undefined, '4')
    const level6 = buildDesignTokenCSS(undefined, undefined, undefined, '6')
    expect(level2).toContain('--transform-card-hover:-1px')
    expect(level4).toContain('--transform-card-hover:-2px')
    expect(level6).toContain('--transform-card-hover:-3px')
  })

  it('unknown elevationStyle falls back to flat', () => {
    const css = buildDesignTokenCSS(undefined, undefined, undefined, 'nonexistent')
    expect(css).toContain('--shadow-card-rest:none')
  })

  it('elevation tokens reference var(--shadow-rgb) (not hardcoded color)', () => {
    const css = buildDesignTokenCSS(undefined, undefined, undefined, '4')
    expect(css).toContain('var(--shadow-rgb)')
    expect(css).not.toMatch(/rgb\(\d+ \d+ \d+/)
  })
})

describe('buildDesignTokenCSS motionTempo', () => {
  it('snappy outputs fastest UI values', () => {
    const css = buildDesignTokenCSS(undefined, undefined, undefined, undefined, 'snappy')
    expect(css).toContain('--motion-ui-fast:150ms')
    expect(css).toContain('--motion-ui-base:250ms')
    expect(css).toContain('--motion-ui-slow:400ms')
  })

  it('balanced outputs mid-range UI values', () => {
    const css = buildDesignTokenCSS(undefined, undefined, undefined, undefined, 'balanced')
    expect(css).toContain('--motion-ui-fast:200ms')
    expect(css).toContain('--motion-ui-base:325ms')
    expect(css).toContain('--motion-ui-slow:500ms')
  })

  it('relaxed outputs slowest UI values', () => {
    const css = buildDesignTokenCSS(undefined, undefined, undefined, undefined, 'relaxed')
    expect(css).toContain('--motion-ui-fast:250ms')
    expect(css).toContain('--motion-ui-base:400ms')
    expect(css).toContain('--motion-ui-slow:600ms')
  })

  it('null/undefined motionTempo defaults to relaxed', () => {
    const cssNull    = buildDesignTokenCSS(undefined, undefined, undefined, undefined, null)
    const cssDefault = buildDesignTokenCSS()
    expect(cssNull).toContain('--motion-ui-fast:250ms')
    expect(cssDefault).toContain('--motion-ui-fast:250ms')
  })

  it('unknown motionTempo falls back to relaxed', () => {
    const css = buildDesignTokenCSS(undefined, undefined, undefined, undefined, 'turbo')
    expect(css).toContain('--motion-ui-fast:250ms')
  })

  it('structural tokens are always fixed regardless of motionTempo', () => {
    for (const tempo of ['snappy', 'balanced', 'relaxed', null]) {
      const css = buildDesignTokenCSS(undefined, undefined, undefined, undefined, tempo)
      expect(css).toContain('--motion-structural-fast:150ms')
      expect(css).toContain('--motion-structural-base:250ms')
      expect(css).toContain('--motion-structural-slow:400ms')
    }
  })

  it('snappy UI values are all faster than relaxed UI values', () => {
    const snappy  = buildDesignTokenCSS(undefined, undefined, undefined, undefined, 'snappy')
    const relaxed = buildDesignTokenCSS(undefined, undefined, undefined, undefined, 'relaxed')
    const extract = (css: string, token: string) =>
      parseInt(css.match(new RegExp(`${token}:(\\d+)ms`))?.[1] ?? '0', 10)

    expect(extract(snappy, '--motion-ui-fast')).toBeLessThan(extract(relaxed, '--motion-ui-fast'))
    expect(extract(snappy, '--motion-ui-base')).toBeLessThan(extract(relaxed, '--motion-ui-base'))
    expect(extract(snappy, '--motion-ui-slow')).toBeLessThan(extract(relaxed, '--motion-ui-slow'))
  })
})

// ─── marketingScale tokens ────────────────────────────────────────────────────

describe('buildDesignTokenCSS marketingScale', () => {
  it('default is opt-in: emits no --marketing-* vars when undefined', () => {
    const css = buildDesignTokenCSS()
    expect(css).not.toContain('--marketing-h1')
    expect(css).not.toContain('--marketing-h2')
    expect(css).not.toContain('--marketing-h3')
    expect(css).not.toContain('--marketing-h4')
  })

  it('"default" emits no --marketing-* vars (utilities fall back to standard)', () => {
    const css = buildDesignTokenCSS(undefined, undefined, undefined, undefined, undefined, 'default')
    expect(css).not.toContain('--marketing-h1')
  })

  it('null emits no --marketing-* vars', () => {
    const css = buildDesignTokenCSS(undefined, undefined, undefined, undefined, undefined, null)
    expect(css).not.toContain('--marketing-h1')
  })

  it('unknown value emits no --marketing-* vars (graceful fallback)', () => {
    const css = buildDesignTokenCSS(undefined, undefined, undefined, undefined, undefined, 'xl')
    expect(css).not.toContain('--marketing-h1')
  })

  it('sm — Perfect Fourth ratio values', () => {
    const css = buildDesignTokenCSS(undefined, undefined, undefined, undefined, undefined, 'sm')
    expect(css).toContain('--marketing-h1:4.214rem')
    expect(css).toContain('--marketing-h2:3.161rem')
    expect(css).toContain('--marketing-h3:2.371rem')
    expect(css).toContain('--marketing-h4:1.778rem')
  })

  it('md — Augmented Fourth ratio values', () => {
    const css = buildDesignTokenCSS(undefined, undefined, undefined, undefined, undefined, 'md')
    expect(css).toContain('--marketing-h1:5.657rem')
    expect(css).toContain('--marketing-h2:4rem')
    expect(css).toContain('--marketing-h3:2.828rem')
    expect(css).toContain('--marketing-h4:2rem')
  })

  it('lg — Golden Ratio values, H1 capped at 8rem', () => {
    const css = buildDesignTokenCSS(undefined, undefined, undefined, undefined, undefined, 'lg')
    expect(css).toContain('--marketing-h1:8rem')
    expect(css).toContain('--marketing-h2:6.854rem')
    expect(css).toContain('--marketing-h3:4.236rem')
    expect(css).toContain('--marketing-h4:2.618rem')
    // Sanity: capped value (8rem) is less than uncapped ratio⁵ × 16px = 11.09rem
    expect(css).not.toContain('--marketing-h1:11.09rem')
  })

  it('values increase with preset across all four levels', () => {
    const sm = buildDesignTokenCSS(undefined, undefined, undefined, undefined, undefined, 'sm')
    const md = buildDesignTokenCSS(undefined, undefined, undefined, undefined, undefined, 'md')
    const lg = buildDesignTokenCSS(undefined, undefined, undefined, undefined, undefined, 'lg')
    const extract = (css: string, level: string) => {
      const match = css.match(new RegExp(`--marketing-${level}:([\\d.]+)rem`))
      return parseFloat(match?.[1] ?? '0')
    }
    for (const level of ['h1', 'h2', 'h3', 'h4']) {
      expect(extract(md, level)).toBeGreaterThan(extract(sm, level))
      expect(extract(lg, level)).toBeGreaterThan(extract(md, level))
    }
  })
})
