/**
 * The authority answers every fixture case, and the fixture is what the Python
 * side asserts against too.
 *
 * DRAFT ITEM P, THE HALF THAT CANNOT BE CONSOLIDATED. One rule for what a
 * redirect set resolves to, implemented in two languages. `resolveRedirects`
 * here is the authority: it is what the Next build runs and what a visitor
 * receives. `BE/_shared/redirect_resolution.py` in the platform monorepo is a
 * port, needed because the Site Builder App's Redirects screen must show what
 * will serve before the build runs and that screen is served by Python. Two
 * runtimes, neither able to import the other, so the pair is DETECTED rather
 * than consolidated.
 *
 * `fixtures/redirect-resolution-cases.json` is the shared artifact. This file
 * asserts THIS side of it. The monorepo carries a byte-identical copy at
 * `BE/_shared/__tests__/fixtures/` and asserts its own side against that, so
 * neither repo's test depends on the other being checked out — a test that
 * skips when a sibling checkout is missing is invisible to every later sweep,
 * which is a lesson that cost this platform a missed assertion once already.
 *
 * If you change the rule, change the fixture in BOTH repos in the same change.
 * The monorepo test records the file's digest and fails when only one moves.
 *
 * The `rules` values were generated by running this function over the `csv`
 * beside them, never written by hand.
 */
import {describe, expect, it} from 'vitest'
import {readFileSync} from 'node:fs'
import {resolve} from 'node:path'
import {parseRedirectsCsv, resolveRedirects} from '../redirects'

type Case = {
  name: string
  csv: string
  rules: [string, string, number][]
  loops: [string, string][]
  duplicates: [string, string, string][]
  flattened: [string, string, string, number][]
}

const fixture = JSON.parse(
  readFileSync(resolve(__dirname, 'fixtures/redirect-resolution-cases.json'), 'utf8'),
) as {cases: Case[]}

describe('redirect resolution fixture', () => {
  it('has cases, and covers every shape two implementations have diverged on', () => {
    expect(fixture.cases.length).toBeGreaterThanOrEqual(10)
    const names = fixture.cases.map((c) => c.name).join(' ')
    for (const shape of ['cycle', 'hop cap', 'duplicate', 'self-redirect', 'chain']) {
      expect(names, `the fixture no longer covers a ${shape}`).toContain(shape)
    }
  })

  for (const testCase of fixture.cases) {
    it(testCase.name, () => {
      const {rules, report} = resolveRedirects(parseRedirectsCsv(testCase.csv))
      expect(rules.map((r) => [r.source, r.destination, r.statusCode])).toEqual(
        testCase.rules.map((r) => [r[0], r[1], r[2]]),
      )
      // The REPORT, and not as a nicety: a cycle and an over-cap chain both
      // serve nothing, so a `rules` comparison alone cannot tell them apart.
      // Deleting cycle detection from the Python port left every `rules` value
      // in this fixture identical. The reason is what an operator is told.
      expect(report.loops.map((l) => [l.source, l.reason])).toEqual(
        testCase.loops.map((l) => [l[0], l[1]]),
      )
      expect(
        report.duplicates.map((d) => [d.source, d.kept.destination, d.dropped.destination]),
      ).toEqual(testCase.duplicates.map((d) => [d[0], d[1], d[2]]))
      expect(
        report.flattened.map((f) => [f.source, f.via, f.destination, f.hops]),
      ).toEqual(testCase.flattened.map((f) => [f[0], f[1], f[2], f[3]]))
    })
  }
})
