/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol;

type ArrayOf<T> = Array<
  T & {
    _key: string;
  }
>;

// Source: schema.json
export type PullQuote = {
  text?: string;
  attribution?: string;
};

export type Proof = {
  number?: string;
  caption?: string;
};

export type VideoReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "video";
};

export type Media = {
  kind?: "photo" | "cutout" | "video";
  image?: MediaImage;
  video?: VideoReference;
};

export type SanityImageAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
};

export type MediaImage = {
  asset?: SanityImageAssetReference;
  media?: unknown; // Unable to locate the referenced type "media.image.media" in schema
  hotspot?: SanityImageHotspot;
  crop?: SanityImageCrop;
  alt?: string;
  _type: "image";
};

export type BlockProse = Array<{
  children?: Array<{
    marks?: Array<string>;
    text?: string;
    _type: "span";
    _key: string;
  }>;
  style?: "normal";
  listItem?: "bullet" | "number";
  markDefs?: Array<
    | {
        tokenKey?: string;
        _type: "contentToken";
        _key: string;
      }
    | {
        href?: string;
        blank?: boolean;
        _type: "link";
        _key: string;
      }
  >;
  level?: number;
  _type: "block";
  _key: string;
}>;

export type SiloNavBlock = {
  _type: "siloNavBlock";
  tagline?: string;
  heading?: string;
  description?: string;
  mode?: "allTopLevel" | "manual";
  items?: Array<
    {
      _key: string;
    } & PracticeAreaNavItem
  >;
};

export type AttorneyPageReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "attorneyPage";
};

export type AttorneyHighlightBlock = {
  _type: "attorneyHighlightBlock";
  tagline?: string;
  heading?: string;
  mode?: "all" | "manual";
  attorneys?: Array<
    {
      _key: string;
    } & AttorneyPageReference
  >;
};

export type CaseResultReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "caseResult";
};

export type CaseResultsBlock = {
  _type: "caseResultsBlock";
  heading?: string;
  intro?: string;
  caseResults?: Array<
    {
      _key: string;
    } & CaseResultReference
  >;
  ctaButton?: CtaButton;
};

export type PracticeAreaReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "practiceArea";
};

export type NarrativeBlock = {
  _type: "narrativeBlock";
  heading?: string;
  body?: BlockProse;
  image?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  ctaButton?: CtaButton;
  internalLinks?: Array<{
    page?: PracticeAreaReference;
    anchorText?: string;
    _type: "internalLink";
    _key: string;
  }>;
};

export type DifferentiatorBlock = {
  _type: "differentiatorBlock";
  heading?: string;
  intro?: string;
  differentiators?: Array<{
    title?: string;
    body?: string;
    _type: "differentiator";
    _key: string;
  }>;
};

export type BadgeReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "badge";
};

export type BadgesBlock = {
  _type: "badgesBlock";
  heading?: string;
  description?: string;
  badges?: Array<
    {
      _key: string;
    } & BadgeReference
  >;
};

export type ReviewsSectionInline = {
  _type: "reviewsSectionInline";
  layout?: "stacked" | "split";
  tagline?: string;
  heading?: string;
  description?: string;
  buttons?: Array<
    {
      _key: string;
    } & CtaButton
  >;
  reviewsEmbed?: string;
  surface?: "light" | "tint" | "dark" | "accent" | "image" | "pattern";
  sectionBackgroundImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  inset?: boolean;
  edgeBottom?: "flat" | "angled";
  overlapPrevious?: "none" | "small" | "large";
  spacing?: "compact" | "normal" | "spacious";
};

export type ContentSectionInline = {
  _type: "contentSectionInline";
  layout?: "split" | "twoColumnText" | "statement" | "ribbon" | "statRow";
  mediaSide?: "left" | "right";
  tagline?: string;
  heading?: string;
  headingEmphasis?: string;
  body?: BlockProse;
  items?: Array<{
    title?: string;
    body?: string;
    _type: "contentSectionItem";
    _key: string;
  }>;
  pullQuote?: PullQuote;
  proof?: Proof;
  badges?: Array<
    {
      _key: string;
    } & BadgeReference
  >;
  buttons?: Array<
    {
      _key: string;
    } & CtaButton
  >;
  showPhone?: boolean;
  media?: Media;
  imageTreatment?:
    "inherit" | "plain" | "framed" | "slab" | "rounded" | "scrim" | "tint";
  marquee?: boolean;
  surface?: "light" | "tint" | "dark" | "accent" | "image" | "pattern";
  sectionBackgroundImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  inset?: boolean;
  edgeBottom?: "flat" | "angled";
  overlapPrevious?: "none" | "small" | "large";
  spacing?: "compact" | "normal" | "spacious";
};

export type VideoSectionInline = {
  _type: "videoSectionInline";
  tagline?: string;
  heading?: string;
  description?: string;
  layout?: "centered" | "split";
  videos?: Array<
    {
      _key: string;
    } & VideoReference
  >;
  surface?: "light" | "tint" | "dark" | "accent" | "image" | "pattern";
  sectionBackgroundImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  inset?: boolean;
  edgeBottom?: "flat" | "angled";
  overlapPrevious?: "none" | "small" | "large";
  spacing?: "compact" | "normal" | "spacious";
};

export type TestimonialReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "testimonial";
};

export type FeaturedTestimonialInline = {
  _type: "featuredTestimonialInline";
  tagline?: string;
  heading?: string;
  testimonial?: TestimonialReference;
  surface?: "light" | "tint" | "dark" | "accent" | "image" | "pattern";
  sectionBackgroundImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  inset?: boolean;
  edgeBottom?: "flat" | "angled";
  overlapPrevious?: "none" | "small" | "large";
  spacing?: "compact" | "normal" | "spacious";
};

export type TestimonialsGridInline = {
  _type: "testimonialsGridInline";
  tagline?: string;
  heading?: string;
  description?: string;
  testimonials?: Array<
    {
      _key: string;
    } & TestimonialReference
  >;
  surface?: "light" | "tint" | "dark" | "accent" | "image" | "pattern";
  sectionBackgroundImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  inset?: boolean;
  edgeBottom?: "flat" | "angled";
  overlapPrevious?: "none" | "small" | "large";
  spacing?: "compact" | "normal" | "spacious";
};

export type BadgesSectionInline = {
  _type: "badgesSectionInline";
  tagline?: string;
  heading?: string;
  description?: string;
  buttons?: Array<
    {
      _key: string;
    } & CtaButton
  >;
  badges?: Array<
    {
      _key: string;
    } & BadgeReference
  >;
  layout?: "inline" | "centeredGrid" | "split" | "scrolling";
  surface?: "light" | "tint" | "dark" | "accent" | "image" | "pattern";
  sectionBackgroundImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  inset?: boolean;
  edgeBottom?: "flat" | "angled";
  overlapPrevious?: "none" | "small" | "large";
  spacing?: "compact" | "normal" | "spacious";
};

export type CaseResultsSectionInline = {
  _type: "caseResultsSectionInline";
  heading?: string;
  intro?: string;
  caseResults?: Array<
    {
      _key: string;
    } & CaseResultReference
  >;
  ctaButton?: CtaButton;
  surface?: "light" | "tint" | "dark" | "accent" | "image" | "pattern";
  sectionBackgroundImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  inset?: boolean;
  edgeBottom?: "flat" | "angled";
  overlapPrevious?: "none" | "small" | "large";
  spacing?: "compact" | "normal" | "spacious";
};

export type AttorneySectionInline = {
  _type: "attorneySectionInline";
  mode?: "all" | "manual";
  attorneys?: Array<
    {
      _key: string;
    } & AttorneyPageReference
  >;
  tagline?: string;
  heading?: string;
  description?: string;
  layout?: "grid" | "slider";
  cardStyle?: "classic" | "portrait" | "avatar" | "minimal" | "spotlight";
  surface?: "light" | "tint" | "dark" | "accent" | "image" | "pattern";
  sectionBackgroundImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  inset?: boolean;
  edgeBottom?: "flat" | "angled";
  overlapPrevious?: "none" | "small" | "large";
  spacing?: "compact" | "normal" | "spacious";
};

export type PracticeAreaNavInline = {
  _type: "practiceAreaNavInline";
  tagline?: string;
  heading?: string;
  description?: string;
  layout?: "spotlight" | "feature" | "tile" | "inline" | "split";
  gridMode?: "equal" | "bentoLeft" | "bentoMosaic" | "bentoList";
  sectionLayout?: "centered" | "left" | "aside" | "banner";
  mobileDisplay?: "carousel" | "stacked" | "list";
  iconPosition?: "auto" | "top" | "left" | "right" | "none";
  showArrow?: boolean;
  hoverEffects?: Array<string>;
  mode?: "allTopLevel" | "manual";
  items?: Array<
    {
      _key: string;
    } & PracticeAreaNavItem
  >;
  surface?: "light" | "tint" | "dark" | "accent" | "image" | "pattern";
  sectionBackgroundImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  inset?: boolean;
  edgeBottom?: "flat" | "angled";
  overlapPrevious?: "none" | "small" | "large";
  spacing?: "compact" | "normal" | "spacious";
};

export type SidebarTableOfContents = {
  _type: "sidebarTableOfContents";
  enabled?: boolean;
};

export type CtaFormSection = {
  _type: "ctaFormSection";
  tagline?: string;
  heading?: string;
  description?: string;
  buttons?: Array<
    {
      _key: string;
    } & CtaButton
  >;
};

export type GeoPracticeAreaReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "geoPracticeArea";
};

export type ServiceAreaPageReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "serviceAreaPage";
};

export type PracticeAreaNavItem = {
  _type: "practiceAreaNavItem";
  page?:
    PracticeAreaReference | GeoPracticeAreaReference | ServiceAreaPageReference;
  featured?: boolean;
  label?: string;
  description?: string;
  icon?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  image?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
};

export type HomeHeroDesign = {
  _type: "homeHeroDesign";
  skeleton?: "overlay" | "split";
  heightMode?: "content" | "fullViewport";
  contentAlign?: "left" | "center";
  backdrop?: "none" | "image" | "mosaic";
  splitMedia?: "image" | "video";
  splitImageStyle?: "contained" | "full" | "overlap";
  splitImageRatio?:
    | "auto"
    | "anamorphic"
    | "univisium"
    | "widescreen"
    | "landscape"
    | "square"
    | "portrait";
  textTreatment?: "inline" | "overlap";
  mediaSide?: "right" | "left";
  motion?: "none" | "fade" | "entrance" | "stagger" | "staggerRight" | "slide";
  schemeOverride?: "inherit" | "dark" | "light";
  sectionBackgroundImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    fit?: "cover" | "tile";
    _type: "image";
  };
  backgroundImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    fit?: "cover" | "tile";
    _type: "image";
  };
  scrimStyle?: "flat" | "gradient";
  scrimOpacityOverride?: number;
  scrimColor?: "auto" | "action" | "black";
  scrimDirection?:
    | "auto"
    | "to-right"
    | "to-left"
    | "to-top"
    | "to-bottom"
    | "to-top-right"
    | "to-top-left"
    | "to-bottom-right"
    | "to-bottom-left";
  foreground?: boolean;
  foregroundImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  galleryImages?: Array<{
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
    _key: string;
  }>;
  videoUrl?: string;
};

export type HomeHeroContent = {
  _type: "homeHeroContent";
  eyebrow?: string;
  heading?: string;
  description?: string;
  buttons?: Array<
    {
      _key: string;
    } & CtaButton
  >;
};

export type InternalHero = {
  _type: "internalHero";
  heading?: string;
  description?: string;
  buttons?: Array<
    {
      _key: string;
    } & CtaButton
  >;
  buttonsNone?: boolean;
  schemeOverride?: "inherit" | "dark" | "light";
  backgroundImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    fit?: "cover" | "tile";
    _type: "image";
  };
  backgroundNone?: boolean;
  sectionBackgroundImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    fit?: "cover" | "tile";
    _type: "image";
  };
  sectionBackgroundNone?: boolean;
  scrimStyleOverride?: "inherit" | "flat" | "gradient";
  scrimOpacityOverride?: number;
  scrimColorOverride?: "inherit" | "auto" | "action" | "black";
  scrimDirectionOverride?:
    | "inherit"
    | "auto"
    | "to-right"
    | "to-left"
    | "to-top"
    | "to-bottom"
    | "to-top-right"
    | "to-top-left"
    | "to-bottom-right"
    | "to-bottom-left";
  foregroundImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  foregroundNone?: boolean;
};

export type CtaButton = {
  _type: "ctaButton";
  title?: string;
  url?: string;
  variant?: "primary" | "secondary" | "link";
};

export type OfficeHours = {
  _type: "officeHours";
  title?: string;
};

export type ContentToken = {
  _type: "contentToken";
  tokenKey?: string;
};

export type BlockContent = Array<
  | {
      children?: Array<
        | {
            marks?: Array<string>;
            text?: string;
            _type: "span";
            _key: string;
          }
        | ({
            _key: string;
          } & ContentToken)
      >;
      style?: "normal" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
      listItem?: "bullet" | "number";
      markDefs?: Array<
        | {
            tokenKey?: string;
            _type: "contentToken";
            _key: string;
          }
        | {
            href?: string;
            blank?: boolean;
            _type: "link";
            _key: string;
          }
      >;
      level?: number;
      _type: "block";
      _key: string;
    }
  | ({
      _key: string;
    } & OfficeHours)
  | {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      alt?: string;
      caption?: string;
      _type: "image";
      _key: string;
    }
>;

export type SiteFormReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "siteForm";
};

export type SidebarFormEmbed = {
  _id: string;
  _type: "sidebarFormEmbed";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  header?: string;
  description?: string;
  form?: SiteFormReference;
};

export type SidebarCtaBox = {
  _id: string;
  _type: "sidebarCtaBox";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  header?: string;
  supportingText1?: string;
  supportingText2?: string;
  phoneNumber?: string;
  button?: CtaButton;
  layout?: "left" | "centered";
};

export type SidebarAttorneyList = {
  _id: string;
  _type: "sidebarAttorneyList";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  header?: string;
  mode?: "practiceArea" | "manual" | "all";
  practiceAreaPage?: PracticeAreaReference;
  layout?: "list" | "avatar";
  attorneys?: Array<
    {
      _key: string;
    } & AttorneyPageReference
  >;
};

export type GeneralPageReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "generalPage";
};

export type AboutPageReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "aboutPage";
};

export type ContactPageReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "contactPage";
};

export type FaqPageReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "faqPage";
};

export type LocationPageReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "locationPage";
};

export type LandingPageReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "landingPage";
};

export type ReviewPageReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "reviewPage";
};

export type BlogPostReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "blogPost";
};

export type SidebarNav = {
  _id: string;
  _type: "sidebarNav";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  header?: string;
  description?: string;
  mode?:
    "practiceArea" | "geoPracticeArea" | "custom" | "recentPosts" | "faqPosts";
  postCount?: number;
  links?: ArrayOf<
    | PracticeAreaReference
    | GeoPracticeAreaReference
    | GeneralPageReference
    | AboutPageReference
    | ContactPageReference
    | FaqPageReference
    | LocationPageReference
    | ServiceAreaPageReference
    | LandingPageReference
    | ReviewPageReference
    | BlogPostReference
  >;
};

export type TestimonialsGridReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "testimonialsGrid";
};

export type FeaturedTestimonialReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "featuredTestimonial";
};

export type CtaSectionReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "ctaSection";
};

export type ContentSectionReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "contentSection";
};

export type CaseResultsSectionReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "caseResultsSection";
};

export type FaqSectionReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "faqSection";
};

export type BadgesSectionReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "badgesSection";
};

export type AttorneySectionReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "attorneySection";
};

export type ReviewsSectionReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "reviewsSection";
};

export type VideoSectionReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "videoSection";
};

export type VideoIndex = {
  _id: string;
  _type: "videoIndex";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  navLabel?: string;
  seoTitle?: string;
  metaDescription?: string;
  ogTitle?: string;
  ogDescription?: string;
  ogImageOverride?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  noIndex?: boolean;
  noFollow?: boolean;
  canonicalUrl?: string;
  hero?: InternalHero;
  tagline?: string;
  heading?: string;
  description?: string;
  featuredVideo?: VideoReference;
  videos?: Array<
    {
      _key: string;
    } & VideoReference
  >;
  sections?: ArrayOf<
    | TestimonialsGridReference
    | FeaturedTestimonialReference
    | CtaSectionReference
    | ContentSectionReference
    | CaseResultsSectionReference
    | FaqSectionReference
    | BadgesSectionReference
    | AttorneySectionReference
    | ReviewsSectionReference
    | VideoSectionReference
  >;
  hideCtaForm?: boolean;
  ctaFormOverride?: CtaFormSection;
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top?: number;
  bottom?: number;
  left?: number;
  right?: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x?: number;
  y?: number;
  height?: number;
  width?: number;
};

export type Slug = {
  _type: "slug";
  current?: string;
  source?: string;
};

export type ContentSection = {
  _id: string;
  _type: "contentSection";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  layout?: "split" | "twoColumnText" | "statement" | "ribbon" | "statRow";
  mediaSide?: "left" | "right";
  tagline?: string;
  heading?: string;
  headingEmphasis?: string;
  body?: BlockProse;
  items?: Array<{
    title?: string;
    body?: string;
    _type: "contentSectionItem";
    _key: string;
  }>;
  pullQuote?: {
    text?: string;
    attribution?: string;
  };
  proof?: {
    number?: string;
    caption?: string;
  };
  badges?: Array<
    {
      _key: string;
    } & BadgeReference
  >;
  buttons?: Array<
    {
      _key: string;
    } & CtaButton
  >;
  showPhone?: boolean;
  media?: {
    kind?: "photo" | "cutout" | "video";
    image?: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      alt?: string;
      _type: "image";
    };
    video?: VideoReference;
  };
  imageTreatment?:
    "inherit" | "plain" | "framed" | "slab" | "rounded" | "scrim" | "tint";
  marquee?: boolean;
  surface?: "light" | "tint" | "dark" | "accent" | "image" | "pattern";
  sectionBackgroundImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  inset?: boolean;
  edgeBottom?: "flat" | "angled";
  overlapPrevious?: "none" | "small" | "large";
  spacing?: "compact" | "normal" | "spacious";
};

export type CaseResultsSection = {
  _id: string;
  _type: "caseResultsSection";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  heading?: string;
  intro?: string;
  caseResults?: Array<
    {
      _key: string;
    } & CaseResultReference
  >;
  ctaButton?: CtaButton;
  surface?: "light" | "tint" | "dark" | "accent" | "image" | "pattern";
  sectionBackgroundImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  inset?: boolean;
  edgeBottom?: "flat" | "angled";
  overlapPrevious?: "none" | "small" | "large";
  spacing?: "compact" | "normal" | "spacious";
};

export type PracticeAreaNav = {
  _id: string;
  _type: "practiceAreaNav";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  tagline?: string;
  heading?: string;
  description?: string;
  layout?: "spotlight" | "feature" | "tile" | "inline" | "split";
  gridMode?: "equal" | "bentoLeft" | "bentoMosaic" | "bentoList";
  sectionLayout?: "centered" | "left" | "aside" | "banner";
  mobileDisplay?: "carousel" | "stacked" | "list";
  iconPosition?: "auto" | "top" | "left" | "right" | "none";
  showArrow?: boolean;
  hoverEffects?: Array<string>;
  mode?: "manual" | "allTopLevel";
  items?: Array<
    {
      _key: string;
    } & PracticeAreaNavItem
  >;
  surface?: "light" | "tint" | "dark" | "accent" | "image" | "pattern";
  sectionBackgroundImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  inset?: boolean;
  edgeBottom?: "flat" | "angled";
  overlapPrevious?: "none" | "small" | "large";
  spacing?: "compact" | "normal" | "spacious";
};

export type VideoSection = {
  _id: string;
  _type: "videoSection";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  tagline?: string;
  heading?: string;
  description?: string;
  layout?: "centered" | "split";
  videos?: Array<
    {
      _key: string;
    } & VideoReference
  >;
  surface?: "light" | "tint" | "dark" | "accent" | "image" | "pattern";
  sectionBackgroundImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  inset?: boolean;
  edgeBottom?: "flat" | "angled";
  overlapPrevious?: "none" | "small" | "large";
  spacing?: "compact" | "normal" | "spacious";
};

export type ReviewsSection = {
  _id: string;
  _type: "reviewsSection";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  layout?: "stacked" | "split";
  tagline?: string;
  heading?: string;
  description?: string;
  buttons?: Array<
    {
      _key: string;
    } & CtaButton
  >;
  reviewsEmbed?: string;
  surface?: "light" | "tint" | "dark" | "accent" | "image" | "pattern";
  sectionBackgroundImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  inset?: boolean;
  edgeBottom?: "flat" | "angled";
  overlapPrevious?: "none" | "small" | "large";
  spacing?: "compact" | "normal" | "spacious";
};

export type AttorneySection = {
  _id: string;
  _type: "attorneySection";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  practiceAreaPage?: PracticeAreaReference;
  mode?: "practiceArea" | "manual" | "all";
  attorneys?: Array<
    {
      _key: string;
    } & AttorneyPageReference
  >;
  tagline?: string;
  heading?: string;
  description?: string;
  layout?: "grid" | "slider";
  cardStyle?: "classic" | "portrait" | "avatar" | "minimal" | "spotlight";
  surface?: "light" | "tint" | "dark" | "accent" | "image" | "pattern";
  sectionBackgroundImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  inset?: boolean;
  edgeBottom?: "flat" | "angled";
  overlapPrevious?: "none" | "small" | "large";
  spacing?: "compact" | "normal" | "spacious";
};

export type BadgesSection = {
  _id: string;
  _type: "badgesSection";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  tagline?: string;
  heading?: string;
  description?: string;
  buttons?: Array<
    {
      _key: string;
    } & CtaButton
  >;
  badges?: Array<
    {
      _key: string;
    } & BadgeReference
  >;
  layout?: "inline" | "centeredGrid" | "split" | "scrolling";
  surface?: "light" | "tint" | "dark" | "accent" | "image" | "pattern";
  sectionBackgroundImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  inset?: boolean;
  edgeBottom?: "flat" | "angled";
  overlapPrevious?: "none" | "small" | "large";
  spacing?: "compact" | "normal" | "spacious";
};

export type FaqItemReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "faqItem";
};

export type FaqSection = {
  _id: string;
  _type: "faqSection";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  heading?: string;
  description?: string;
  questions?: Array<
    {
      _key: string;
    } & FaqItemReference
  >;
  footerHeading?: string;
  footerDescription?: string;
  footerButton?: CtaButton;
  surface?: "light" | "tint" | "dark" | "accent" | "image" | "pattern";
  sectionBackgroundImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  inset?: boolean;
  edgeBottom?: "flat" | "angled";
  overlapPrevious?: "none" | "small" | "large";
  spacing?: "compact" | "normal" | "spacious";
};

export type CtaSection = {
  _id: string;
  _type: "ctaSection";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  tagline?: string;
  heading?: string;
  description?: string;
  buttons?: Array<
    {
      _key: string;
    } & CtaButton
  >;
  image?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  layout?: "centered" | "split" | "background" | "textOnly";
  surface?: "light" | "tint" | "dark" | "accent" | "image" | "pattern";
  sectionBackgroundImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  inset?: boolean;
  edgeBottom?: "flat" | "angled";
  overlapPrevious?: "none" | "small" | "large";
  spacing?: "compact" | "normal" | "spacious";
};

export type FeaturedTestimonial = {
  _id: string;
  _type: "featuredTestimonial";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  tagline?: string;
  heading?: string;
  testimonial?: TestimonialReference;
  surface?: "light" | "tint" | "dark" | "accent" | "image" | "pattern";
  sectionBackgroundImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  inset?: boolean;
  edgeBottom?: "flat" | "angled";
  overlapPrevious?: "none" | "small" | "large";
  spacing?: "compact" | "normal" | "spacious";
};

export type TestimonialsGrid = {
  _id: string;
  _type: "testimonialsGrid";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  tagline?: string;
  heading?: string;
  description?: string;
  testimonials?: Array<
    {
      _key: string;
    } & TestimonialReference
  >;
  surface?: "light" | "tint" | "dark" | "accent" | "image" | "pattern";
  sectionBackgroundImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  inset?: boolean;
  edgeBottom?: "flat" | "angled";
  overlapPrevious?: "none" | "small" | "large";
  spacing?: "compact" | "normal" | "spacious";
};

export type Badge = {
  _id: string;
  _type: "badge";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  image?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  grantingBody?: string;
  year?: string;
  explanation?: string;
  url?: string;
};

export type PressItem = {
  _id: string;
  _type: "pressItem";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  outlet?: string;
  headline?: string;
  url?: string;
  date?: string;
  outletLogo?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
};

export type CaseResult = {
  _id: string;
  _type: "caseResult";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  amount?: string;
  caseType?: string;
  caption?: string;
  year?: number;
  practiceArea?: PracticeAreaReference;
};

export type FaqItem = {
  _id: string;
  _type: "faqItem";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  question?: string;
  slug?: Slug;
  category?:
    | "general"
    | "family-law"
    | "estate-planning"
    | "probate"
    | "business-law"
    | "real-estate-law"
    | "construction-law"
    | "employment-law"
    | "personal-injury"
    | "workers-compensation"
    | "litigation";
  tags?: Array<string>;
  answer?: BlockContent;
};

export type TestimonialsPage = {
  _id: string;
  _type: "testimonialsPage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  navLabel?: string;
  seoTitle?: string;
  metaDescription?: string;
  ogTitle?: string;
  ogDescription?: string;
  ogImageOverride?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  noIndex?: boolean;
  noFollow?: boolean;
  canonicalUrl?: string;
  hero?: InternalHero;
  testimonials?: Array<
    {
      _key: string;
    } & TestimonialReference
  >;
  sections?: ArrayOf<
    | TestimonialsGridReference
    | FeaturedTestimonialReference
    | CtaSectionReference
    | ContentSectionReference
    | CaseResultsSectionReference
    | FaqSectionReference
    | BadgesSectionReference
    | AttorneySectionReference
    | ReviewsSectionReference
    | VideoSectionReference
  >;
  hideCtaForm?: boolean;
  ctaFormOverride?: CtaFormSection;
};

export type Testimonial = {
  _id: string;
  _type: "testimonial";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  quote?: string;
  name?: string;
  caseType?: string;
  numberOfStars?: 1 | 2 | 3 | 4 | 5;
  avatar?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
};

export type HeroSettings = {
  _id: string;
  _type: "heroSettings";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  homepageHero?: HomeHeroDesign;
  scheme?: "dark" | "light";
  backgroundImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    fit?: "cover" | "tile";
    _type: "image";
  };
  sectionBackgroundImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    fit?: "cover" | "tile";
    _type: "image";
  };
  scrimStyle?: "flat" | "gradient";
  scrimOpacity?: number;
  scrimColor?: "auto" | "action" | "black";
  scrimDirection?:
    | "auto"
    | "to-right"
    | "to-left"
    | "to-top"
    | "to-bottom"
    | "to-top-right"
    | "to-top-left"
    | "to-bottom-right"
    | "to-bottom-left";
  foregroundImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  defaultButtons?: Array<
    {
      _key: string;
    } & CtaButton
  >;
};

export type FooterSettings = {
  _id: string;
  _type: "footerSettings";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  ctaText?: string;
  ctaUrl?: string;
  footerLayout?:
    | "anchor"
    | "crest"
    | "pillar"
    | "meridian"
    | "districts"
    | "switchboard"
    | "beacon";
  footerScheme?: "dark" | "light";
  form?: SiteFormReference;
  actionButton1Label?: string;
  actionButton1Url?: string;
  actionButton2Label?: string;
  actionButton2Url?: string;
  column1?: Array<{
    label?: string;
    href?: string;
    _type: "footerLink";
    _key: string;
  }>;
  column2?: Array<{
    label?: string;
    href?: string;
    _type: "footerLink";
    _key: string;
  }>;
  facebookUrl?: string;
  instagramUrl?: string;
  twitterUrl?: string;
  linkedInUrl?: string;
  youTubeUrl?: string;
  avvoUrl?: string;
  justiaUrl?: string;
  findLawUrl?: string;
  martindaleUrl?: string;
  lawyersComUrl?: string;
  yelpUrl?: string;
  superLawyersUrl?: string;
  lawInfoUrl?: string;
};

export type MainNavigation = {
  _id: string;
  _type: "mainNavigation";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  headerLayout?:
    "ridge" | "apex" | "ledge" | "spire" | "mesa" | "prism" | "crest";
  mobileLayout?:
    "standard" | "bar-top" | "bar-bottom" | "phone-split" | "logo-split";
  defaultScheme?: "light" | "dark" | "transparent-light" | "transparent-dark";
  heroMerge?: boolean;
  sticky?: boolean;
  scrolledScheme?: "light" | "dark" | "glass" | "glass-dark";
  stickyHideSupplementary?: boolean;
  compactStyle?: "docked" | "float";
  topBarDesktop?: boolean;
  topBarMobile?: boolean;
  topBarPinSide?: "none" | "left" | "right";
  topBarLeft?: string;
  topBarRight?: string;
  topBarStyle?: "primary" | "secondary" | "dark";
  headerPhoneTagline?: string;
  headerPhone?: string;
  headerPhone2?: string;
  headerCtaLabel?: string;
  headerCtaUrl?: string;
  headerCtaLabel2?: string;
  headerCtaUrl2?: string;
  items?: Array<
    | {
        label?: string;
        href?: string;
        children?: Array<{
          label?: string;
          href?: string;
          _type: "navSubItem";
          _key: string;
        }>;
        _type: "navItemStandard";
        _key: string;
      }
    | {
        label?: string;
        href?: string;
        attorneyOrder?: Array<
          {
            _key: string;
          } & AttorneyPageReference
        >;
        _type: "navItemAttorneys";
        _key: string;
      }
    | {
        label?: string;
        href?: string;
        displayMode?: "flat" | "hierarchy";
        practiceAreaOrder?: Array<
          {
            _key: string;
          } & PracticeAreaReference
        >;
        _type: "navItemPracticeAreas";
        _key: string;
      }
  >;
};

export type GlobalCta = {
  _id: string;
  _type: "globalCta";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  layout?: "centered" | "split";
  tagline?: string;
  heading?: string;
  description?: string;
  buttons?: Array<
    {
      _key: string;
    } & CtaButton
  >;
  form?: SiteFormReference;
};

export type EventIndex = {
  _id: string;
  _type: "eventIndex";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  navLabel?: string;
  seoTitle?: string;
  metaDescription?: string;
  ogTitle?: string;
  ogDescription?: string;
  ogImageOverride?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  noIndex?: boolean;
  noFollow?: boolean;
  canonicalUrl?: string;
  hero?: InternalHero;
  sections?: ArrayOf<
    | TestimonialsGridReference
    | FeaturedTestimonialReference
    | CtaSectionReference
    | ContentSectionReference
    | CaseResultsSectionReference
    | FaqSectionReference
    | BadgesSectionReference
    | AttorneySectionReference
    | ReviewsSectionReference
    | VideoSectionReference
  >;
  hideCtaForm?: boolean;
  ctaFormOverride?: CtaFormSection;
};

export type EventCategoryReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "eventCategory";
};

export type EventPage = {
  _id: string;
  _type: "eventPage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  navLabel?: string;
  seoTitle?: string;
  metaDescription?: string;
  ogTitle?: string;
  ogDescription?: string;
  ogImageOverride?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  noIndex?: boolean;
  noFollow?: boolean;
  canonicalUrl?: string;
  eventDate?: string;
  eventEndDate?: string;
  eventType?: "seminar" | "workshop" | "webinar" | "community-event";
  category?: EventCategoryReference;
  locationType?: "in-person" | "virtual" | "hybrid";
  locationAddress?: string;
  virtualLink?: string;
  attorneys?: Array<
    {
      _key: string;
    } & AttorneyPageReference
  >;
  registrationUrl?: string;
  registrationCta?: string;
  registrationForm?: SiteFormReference;
  body?: BlockContent;
  hideCtaForm?: boolean;
  ctaFormOverride?: CtaFormSection;
};

export type EventCategory = {
  _id: string;
  _type: "eventCategory";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
};

export type ReviewPage = {
  _id: string;
  _type: "reviewPage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  metaDescription?: string;
  navLabel?: string;
  h1?: string;
  blurb?: BlockContent;
  reviewLinks?: Array<{
    platform?:
      | "google"
      | "facebook"
      | "findlaw"
      | "martindale"
      | "lawyersCom"
      | "avvo"
      | "yelp"
      | "other";
    url?: string;
    label?: string;
    _type: "reviewLink";
    _key: string;
  }>;
  feedbackForm?: SiteFormReference;
  noIndex?: boolean;
  noFollow?: boolean;
};

export type LandingPage = {
  _id: string;
  _type: "landingPage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  navLabel?: string;
  seoTitle?: string;
  metaDescription?: string;
  ogTitle?: string;
  ogDescription?: string;
  ogImageOverride?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  noIndex?: boolean;
  noFollow?: boolean;
  canonicalUrl?: string;
  hideCtaForm?: boolean;
  campaignForm?: SiteFormReference;
  hero?: InternalHero;
  sections?: ArrayOf<
    | TestimonialsGridReference
    | FeaturedTestimonialReference
    | CtaSectionReference
    | ContentSectionReference
    | CaseResultsSectionReference
    | FaqSectionReference
    | BadgesSectionReference
    | AttorneySectionReference
    | ReviewsSectionReference
    | VideoSectionReference
  >;
};

export type StaffPageReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "staffPage";
};

export type StaffIndex = {
  _id: string;
  _type: "staffIndex";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  navLabel?: string;
  seoTitle?: string;
  metaDescription?: string;
  ogTitle?: string;
  ogDescription?: string;
  ogImageOverride?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  noIndex?: boolean;
  noFollow?: boolean;
  canonicalUrl?: string;
  hero?: InternalHero;
  orderedStaff?: Array<
    {
      _key: string;
    } & StaffPageReference
  >;
  sections?: ArrayOf<
    | TestimonialsGridReference
    | FeaturedTestimonialReference
    | CtaSectionReference
    | ContentSectionReference
    | CaseResultsSectionReference
    | FaqSectionReference
    | BadgesSectionReference
    | ReviewsSectionReference
    | VideoSectionReference
  >;
  hideCtaForm?: boolean;
  ctaFormOverride?: CtaFormSection;
};

export type StaffPage = {
  _id: string;
  _type: "staffPage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  navLabel?: string;
  seoTitle?: string;
  metaDescription?: string;
  ogTitle?: string;
  ogDescription?: string;
  ogImageOverride?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  noIndex?: boolean;
  noFollow?: boolean;
  canonicalUrl?: string;
  firstName?: string;
  lastName?: string;
  jobTitle?: string;
  photo?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  email?: string;
  phone?: string;
  biography?: BlockContent;
  location?: LocationPageReference;
  hideCtaForm?: boolean;
  ctaFormOverride?: CtaFormSection;
};

export type AttorneyIndex = {
  _id: string;
  _type: "attorneyIndex";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  navLabel?: string;
  seoTitle?: string;
  metaDescription?: string;
  ogTitle?: string;
  ogDescription?: string;
  ogImageOverride?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  noIndex?: boolean;
  noFollow?: boolean;
  canonicalUrl?: string;
  hero?: InternalHero;
  orderedAttorneys?: Array<
    {
      _key: string;
    } & AttorneyPageReference
  >;
  sections?: ArrayOf<
    | TestimonialsGridReference
    | FeaturedTestimonialReference
    | CtaSectionReference
    | ContentSectionReference
    | CaseResultsSectionReference
    | FaqSectionReference
    | BadgesSectionReference
    | ReviewsSectionReference
    | VideoSectionReference
  >;
  hideCtaForm?: boolean;
  ctaFormOverride?: CtaFormSection;
};

export type AttorneyPage = {
  _id: string;
  _type: "attorneyPage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  navLabel?: string;
  h1?: string;
  ctaOverride?: {
    label?: string;
    url?: string;
  };
  seoTitle?: string;
  metaDescription?: string;
  ogTitle?: string;
  ogDescription?: string;
  ogImageOverride?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  noIndex?: boolean;
  noFollow?: boolean;
  canonicalUrl?: string;
  firstName?: string;
  lastName?: string;
  middleName?: string;
  suffix?: string;
  jobTitle?: string;
  photo?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  fullBiography?: BlockContent;
  practiceAreas?: Array<{
    label?: string;
    page?: PracticeAreaReference;
    _key: string;
  }>;
  email?: string;
  showEmail?: boolean;
  linkedIn?: string;
  location?: LocationPageReference;
  showLocations?: boolean;
  videos?: Array<
    {
      _key: string;
    } & VideoReference
  >;
  yearAdmittedToBar?: string;
  educationDegrees?: BlockContent;
  barAdmissions?: BlockContent;
  stateBarAdmissions?: BlockContent;
  certifiedLegalSpecialties?: BlockContent;
  honors?: BlockContent;
  professionalAssociations?: BlockContent;
  proBonoActivities?: BlockContent;
  publications?: BlockContent;
  presentationsSeminars?: BlockContent;
  representativeCases?: BlockContent;
  pastPositions?: BlockContent;
  avvo?: string;
  superLawyers?: string;
  findLaw?: string;
  martindale?: string;
  lawyersCom?: string;
  justia?: string;
  hideCtaForm?: boolean;
  ctaFormOverride?: CtaFormSection;
};

export type LocationReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "location";
};

export type SidebarNavReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sidebarNav";
};

export type SidebarAttorneyListReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sidebarAttorneyList";
};

export type SidebarCtaBoxReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sidebarCtaBox";
};

export type SidebarFormEmbedReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sidebarFormEmbed";
};

export type LocationPage = {
  _id: string;
  _type: "locationPage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  locationRef?: LocationReference;
  title?: string;
  slug?: Slug;
  navLabel?: string;
  seoTitle?: string;
  metaDescription?: string;
  ogTitle?: string;
  ogDescription?: string;
  ogImageOverride?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  noIndex?: boolean;
  noFollow?: boolean;
  canonicalUrl?: string;
  hero?: InternalHero;
  body?: BlockContent;
  mapEmbed?: string;
  sidebar?: Array<
    | SidebarNavReference
    | SidebarAttorneyListReference
    | SidebarCtaBoxReference
    | SidebarFormEmbedReference
    | ({
        _key: string;
      } & SidebarTableOfContents)
  >;
  sections?: ArrayOf<
    | TestimonialsGridReference
    | FeaturedTestimonialReference
    | CtaSectionReference
    | ContentSectionReference
    | CaseResultsSectionReference
    | FaqSectionReference
    | BadgesSectionReference
    | AttorneySectionReference
    | ReviewsSectionReference
    | VideoSectionReference
  >;
  hideCtaForm?: boolean;
  ctaFormOverride?: CtaFormSection;
};

export type BlogTag = {
  _id: string;
  _type: "blogTag";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
};

export type BlogCategoryReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "blogCategory";
};

export type BlogTagReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "blogTag";
};

export type BlogPost = {
  _id: string;
  _type: "blogPost";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  navLabel?: string;
  seoTitle?: string;
  metaDescription?: string;
  ogTitle?: string;
  ogDescription?: string;
  ogImageOverride?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  noIndex?: boolean;
  noFollow?: boolean;
  canonicalUrl?: string;
  h1?: string;
  body?: BlockContent;
  useTemplateAsFeaturedImage?: boolean;
  featuredImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  publishedAt?: string;
  lastModified?: string;
  authors?: Array<
    {
      _key: string;
    } & AttorneyPageReference
  >;
  category?: BlogCategoryReference;
  tags?: Array<
    {
      _key: string;
    } & BlogTagReference
  >;
  sidebar?: Array<
    | SidebarNavReference
    | SidebarAttorneyListReference
    | SidebarCtaBoxReference
    | SidebarFormEmbedReference
    | ({
        _key: string;
      } & SidebarTableOfContents)
  >;
  sections?: ArrayOf<
    | TestimonialsGridReference
    | FeaturedTestimonialReference
    | CtaSectionReference
    | ContentSectionReference
    | CaseResultsSectionReference
    | FaqSectionReference
    | BadgesSectionReference
    | AttorneySectionReference
    | ReviewsSectionReference
    | VideoSectionReference
  >;
  hideCtaForm?: boolean;
  ctaFormOverride?: CtaFormSection;
};

export type BlogCategory = {
  _id: string;
  _type: "blogCategory";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  navLabel?: string;
  seoTitle?: string;
  metaDescription?: string;
  ogTitle?: string;
  ogDescription?: string;
  ogImageOverride?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  noIndex?: boolean;
  noFollow?: boolean;
  canonicalUrl?: string;
  h1?: string;
  tagline?: string;
  heading?: string;
  description?: string;
  hideCtaForm?: boolean;
  ctaFormOverride?: CtaFormSection;
};

export type BlogIndex = {
  _id: string;
  _type: "blogIndex";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  navLabel?: string;
  seoTitle?: string;
  metaDescription?: string;
  ogTitle?: string;
  ogDescription?: string;
  ogImageOverride?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  noIndex?: boolean;
  noFollow?: boolean;
  canonicalUrl?: string;
  hero?: InternalHero;
  sections?: ArrayOf<
    | TestimonialsGridReference
    | FeaturedTestimonialReference
    | CtaSectionReference
    | ContentSectionReference
    | CaseResultsSectionReference
    | FaqSectionReference
    | BadgesSectionReference
    | AttorneySectionReference
    | ReviewsSectionReference
    | VideoSectionReference
  >;
  hideCtaForm?: boolean;
  ctaFormOverride?: CtaFormSection;
};

export type FaqPage = {
  _id: string;
  _type: "faqPage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  parentPage?: PracticeAreaReference;
  slug?: Slug;
  navLabel?: string;
  seoTitle?: string;
  metaDescription?: string;
  ogTitle?: string;
  ogDescription?: string;
  ogImageOverride?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  noIndex?: boolean;
  noFollow?: boolean;
  canonicalUrl?: string;
  hero?: InternalHero;
  body?: BlockContent;
  faqItems?: Array<
    {
      _key: string;
    } & FaqItemReference
  >;
  sidebar?: Array<
    | SidebarNavReference
    | SidebarAttorneyListReference
    | SidebarCtaBoxReference
    | SidebarFormEmbedReference
    | ({
        _key: string;
      } & SidebarTableOfContents)
  >;
  sections?: ArrayOf<
    | TestimonialsGridReference
    | FeaturedTestimonialReference
    | CtaSectionReference
    | ContentSectionReference
    | CaseResultsSectionReference
    | FaqSectionReference
    | BadgesSectionReference
    | AttorneySectionReference
    | ReviewsSectionReference
    | VideoSectionReference
  >;
  hideCtaForm?: boolean;
  ctaFormOverride?: CtaFormSection;
};

export type ContactPage = {
  _id: string;
  _type: "contactPage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  navLabel?: string;
  seoTitle?: string;
  metaDescription?: string;
  ogTitle?: string;
  ogDescription?: string;
  ogImageOverride?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  noIndex?: boolean;
  noFollow?: boolean;
  canonicalUrl?: string;
  showHero?: boolean;
  hero?: InternalHero;
  tagline?: string;
  heading?: string;
  description?: string;
  contactForm?: SiteFormReference;
  sections?: ArrayOf<
    | TestimonialsGridReference
    | FeaturedTestimonialReference
    | CtaSectionReference
    | ContentSectionReference
    | CaseResultsSectionReference
    | FaqSectionReference
    | BadgesSectionReference
    | AttorneySectionReference
    | ReviewsSectionReference
    | VideoSectionReference
  >;
};

export type SiteForm = {
  _id: string;
  _type: "siteForm";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  description?: string;
  formEmbed?: string;
};

export type ServiceAreaIndex = {
  _id: string;
  _type: "serviceAreaIndex";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  navLabel?: string;
  seoTitle?: string;
  metaDescription?: string;
  ogTitle?: string;
  ogDescription?: string;
  ogImageOverride?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  noIndex?: boolean;
  noFollow?: boolean;
  canonicalUrl?: string;
  hero?: InternalHero;
  tagline?: string;
  heading?: string;
  description?: string;
  sections?: ArrayOf<
    | TestimonialsGridReference
    | FeaturedTestimonialReference
    | CtaSectionReference
    | ContentSectionReference
    | CaseResultsSectionReference
    | FaqSectionReference
    | BadgesSectionReference
    | AttorneySectionReference
    | ReviewsSectionReference
    | VideoSectionReference
  >;
  hideCtaForm?: boolean;
  ctaFormOverride?: CtaFormSection;
};

export type ServiceAreaPage = {
  _id: string;
  _type: "serviceAreaPage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  parentPage?: ServiceAreaPageReference;
  slug?: Slug;
  navLabel?: string;
  seoTitle?: string;
  metaDescription?: string;
  ogTitle?: string;
  ogDescription?: string;
  ogImageOverride?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  noIndex?: boolean;
  noFollow?: boolean;
  canonicalUrl?: string;
  hero?: InternalHero;
  body?: BlockContent;
  faqItems?: Array<
    {
      _key: string;
    } & FaqItemReference
  >;
  sidebar?: Array<
    | SidebarNavReference
    | SidebarAttorneyListReference
    | SidebarCtaBoxReference
    | SidebarFormEmbedReference
    | ({
        _key: string;
      } & SidebarTableOfContents)
  >;
  sections?: ArrayOf<
    | TestimonialsGridReference
    | FeaturedTestimonialReference
    | CtaSectionReference
    | ContentSectionReference
    | CaseResultsSectionReference
    | FaqSectionReference
    | BadgesSectionReference
    | AttorneySectionReference
    | ReviewsSectionReference
    | VideoSectionReference
  >;
  hideCtaForm?: boolean;
  ctaFormOverride?: CtaFormSection;
};

export type GeoPracticeArea = {
  _id: string;
  _type: "geoPracticeArea";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  parentPage?: GeoPracticeAreaReference;
  slug?: Slug;
  navLabel?: string;
  seoTitle?: string;
  metaDescription?: string;
  ogTitle?: string;
  ogDescription?: string;
  ogImageOverride?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  noIndex?: boolean;
  noFollow?: boolean;
  canonicalUrl?: string;
  hero?: InternalHero;
  body?: BlockContent;
  faqItems?: Array<
    {
      _key: string;
    } & FaqItemReference
  >;
  sidebar?: Array<
    | SidebarNavReference
    | SidebarAttorneyListReference
    | SidebarCtaBoxReference
    | SidebarFormEmbedReference
    | ({
        _key: string;
      } & SidebarTableOfContents)
  >;
  sections?: ArrayOf<
    | TestimonialsGridReference
    | FeaturedTestimonialReference
    | CtaSectionReference
    | ContentSectionReference
    | CaseResultsSectionReference
    | FaqSectionReference
    | BadgesSectionReference
    | AttorneySectionReference
    | ReviewsSectionReference
    | VideoSectionReference
  >;
  hideCtaForm?: boolean;
  ctaFormOverride?: CtaFormSection;
};

export type GeneralPage = {
  _id: string;
  _type: "generalPage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  parentPage?: AboutPageReference | GeneralPageReference;
  slug?: Slug;
  navLabel?: string;
  seoTitle?: string;
  metaDescription?: string;
  ogTitle?: string;
  ogDescription?: string;
  ogImageOverride?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  noIndex?: boolean;
  noFollow?: boolean;
  canonicalUrl?: string;
  hero?: InternalHero;
  body?: BlockContent;
  sidebar?: Array<
    | SidebarNavReference
    | SidebarAttorneyListReference
    | SidebarCtaBoxReference
    | SidebarFormEmbedReference
    | ({
        _key: string;
      } & SidebarTableOfContents)
  >;
  sections?: ArrayOf<
    | TestimonialsGridReference
    | FeaturedTestimonialReference
    | CtaSectionReference
    | ContentSectionReference
    | CaseResultsSectionReference
    | FaqSectionReference
    | BadgesSectionReference
    | AttorneySectionReference
    | ReviewsSectionReference
    | VideoSectionReference
  >;
  hideCtaForm?: boolean;
  ctaFormOverride?: CtaFormSection;
};

export type PracticeAreaNavReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "practiceAreaNav";
};

export type AboutPage = {
  _id: string;
  _type: "aboutPage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  navLabel?: string;
  seoTitle?: string;
  metaDescription?: string;
  ogTitle?: string;
  ogDescription?: string;
  ogImageOverride?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  noIndex?: boolean;
  noFollow?: boolean;
  canonicalUrl?: string;
  hero?: InternalHero;
  body?: BlockContent;
  sidebar?: Array<
    | SidebarNavReference
    | SidebarAttorneyListReference
    | SidebarCtaBoxReference
    | SidebarFormEmbedReference
    | ({
        _key: string;
      } & SidebarTableOfContents)
  >;
  sections?: ArrayOf<
    | TestimonialsGridReference
    | FeaturedTestimonialReference
    | CtaSectionReference
    | ContentSectionReference
    | CaseResultsSectionReference
    | FaqSectionReference
    | BadgesSectionReference
    | AttorneySectionReference
    | ReviewsSectionReference
    | VideoSectionReference
    | PracticeAreaNavReference
  >;
  hideCtaForm?: boolean;
  ctaFormOverride?: CtaFormSection;
};

export type HomePage = {
  _id: string;
  _type: "homePage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  navLabel?: string;
  seoTitle?: string;
  metaDescription?: string;
  ogTitle?: string;
  ogDescription?: string;
  ogImageOverride?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  noIndex?: boolean;
  noFollow?: boolean;
  canonicalUrl?: string;
  hero?: HomeHeroContent;
  reviewsEmbed?: string;
  canvas?: Array<
    | ({
        _key: string;
      } & PracticeAreaNavInline)
    | ({
        _key: string;
      } & AttorneySectionInline)
    | ({
        _key: string;
      } & CaseResultsSectionInline)
    | ({
        _key: string;
      } & BadgesSectionInline)
    | ({
        _key: string;
      } & TestimonialsGridInline)
    | ({
        _key: string;
      } & FeaturedTestimonialInline)
    | ({
        _key: string;
      } & VideoSectionInline)
    | ({
        _key: string;
      } & ContentSectionInline)
    | ({
        _key: string;
      } & ReviewsSectionInline)
    | ({
        _key: string;
      } & NarrativeBlock)
    | ({
        _key: string;
      } & DifferentiatorBlock)
    | ({
        _key: string;
      } & CaseResultsBlock)
    | ({
        _key: string;
      } & AttorneyHighlightBlock)
    | ({
        _key: string;
      } & BadgesBlock)
    | ({
        _key: string;
      } & SiloNavBlock)
  >;
  codaLine?: string;
  sections?: ArrayOf<
    | TestimonialsGridReference
    | FeaturedTestimonialReference
    | CtaSectionReference
    | FaqSectionReference
    | BadgesSectionReference
    | AttorneySectionReference
    | ReviewsSectionReference
    | VideoSectionReference
    | PracticeAreaNavReference
  >;
  hideCtaForm?: boolean;
  ctaFormOverride?: CtaFormSection;
};

export type PracticeArea = {
  _id: string;
  _type: "practiceArea";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  parentPage?: PracticeAreaReference;
  slug?: Slug;
  navLabel?: string;
  seoTitle?: string;
  metaDescription?: string;
  ogTitle?: string;
  ogDescription?: string;
  ogImageOverride?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  noIndex?: boolean;
  noFollow?: boolean;
  canonicalUrl?: string;
  hero?: InternalHero;
  body?: BlockContent;
  faqItems?: Array<
    {
      _key: string;
    } & FaqItemReference
  >;
  sidebar?: Array<
    | SidebarNavReference
    | SidebarAttorneyListReference
    | SidebarCtaBoxReference
    | SidebarFormEmbedReference
    | ({
        _key: string;
      } & SidebarTableOfContents)
  >;
  sections?: ArrayOf<
    | TestimonialsGridReference
    | FeaturedTestimonialReference
    | CtaSectionReference
    | ContentSectionReference
    | CaseResultsSectionReference
    | FaqSectionReference
    | BadgesSectionReference
    | AttorneySectionReference
    | ReviewsSectionReference
    | VideoSectionReference
  >;
  hideCtaForm?: boolean;
  ctaFormOverride?: CtaFormSection;
};

export type Video = {
  _id: string;
  _type: "video";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  youTubeUrl?: string;
  description?: string;
  videoType?:
    | "Firm Overview"
    | "Attorney Bio"
    | "Practice Area"
    | "Testimonial"
    | "Other";
  thumbnail?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  duration?: string;
};

export type SanityFileAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.fileAsset";
};

export type DesignSettings = {
  _id: string;
  _type: "designSettings";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  pageBackground?: {
    kind?: "none" | "texture" | "photo" | "gradient";
    texture?: "pinstripe" | "diagonalHatch" | "diamondLattice" | "scallop";
    image?: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    };
    opacity?: number;
  };
  logoOnLight?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  logoOnDark?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  logoMarkOnLight?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  logoMarkOnDark?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  favicon?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  webclipImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  colorApproach?: "monochromatic" | "complementary" | "analogous-accent";
  primaryColor?: string;
  actionColor?: string;
  accent1Color?: string;
  accent2Color?: string;
  colorPreview?: string;
  fontPairingPreset?:
    1 | 2 | 4 | 5 | 6 | 7 | 9 | 10 | 11 | 12 | 13 | 14 | 15 | 16 | 17 | 18;
  marketingScale?: "default" | "sm" | "md" | "lg";
  taglineStyle?: "plain" | "lined" | "titlecase";
  customFonts?: {
    headingFont?: {
      name?: string;
      regular?: {
        asset?: SanityFileAssetReference;
        media?: unknown;
        _type: "file";
      };
      bold?: {
        asset?: SanityFileAssetReference;
        media?: unknown;
        _type: "file";
      };
      italic?: {
        asset?: SanityFileAssetReference;
        media?: unknown;
        _type: "file";
      };
    };
    bodyFont?: {
      name?: string;
      regular?: {
        asset?: SanityFileAssetReference;
        media?: unknown;
        _type: "file";
      };
      semibold?: {
        asset?: SanityFileAssetReference;
        media?: unknown;
        _type: "file";
      };
      bold?: {
        asset?: SanityFileAssetReference;
        media?: unknown;
        _type: "file";
      };
      italic?: {
        asset?: SanityFileAssetReference;
        media?: unknown;
        _type: "file";
      };
      boldItalic?: {
        asset?: SanityFileAssetReference;
        media?: unknown;
        _type: "file";
      };
    };
  };
  uiRadius?: "sharp" | "subtle" | "rounded" | "soft";
  buttonShape?: "square" | "rounded" | "stadium" | "pill";
  buttonAnimation?: "none" | "sweep" | "fill-center" | "inset" | "lift";
  showBackToTop?: boolean;
  internalHeroBackground?: "dark" | "light";
  siteHeroBackgroundImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    fit?: "cover" | "tile";
    _type: "image";
  };
  siteHeroForegroundImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  heroScrimOpacity?: number;
  tertiaryStyle?: "plain" | "tracked";
  elevationStyle?: "0" | "1" | "2" | "4" | "6";
  sidebarNavIconStyle?: "chevrons" | "arrows" | "none";
  sidebarWidgetHeaderLine?: boolean;
  sidebarItemSeparators?: boolean;
  motionTempo?: "snappy" | "balanced" | "relaxed";
  profileLayout?:
    "splitHero" | "classicSidebar" | "featureGrid" | "premiumHorizontal";
  profileCtaLabel?: string;
  profileCtaUrl?: string;
};

export type SiteSettings = {
  _id: string;
  _type: "siteSettings";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  firmName?: string;
  firmNameShort?: string;
  primaryLocation?: LocationReference;
  timezone?:
    | "America/New_York"
    | "America/Chicago"
    | "America/Denver"
    | "America/Phoenix"
    | "America/Los_Angeles"
    | "America/Anchorage"
    | "Pacific/Honolulu";
  languageCode?: string;
  privacyPolicyUrl?: string;
  disclaimerUrl?: string;
  cookiesUrl?: string;
  resultsDisclaimer?: string;
  cookieBannerText?: string;
  hideFromSearch?: boolean;
  gscVerification?: string;
  scriptsNoConsent?: string;
  scriptsRequireConsent?: string;
};

export type Location = {
  _id: string;
  _type: "location";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  isPrimary?: boolean;
  locationType?: "Physical" | "Virtual" | "Shared" | "Home";
  locationStatus?: "Active" | "Inactive";
  address1?: string;
  address2?: string;
  address3?: string;
  city?: string;
  state?:
    | "Alabama"
    | "Alaska"
    | "Arizona"
    | "Arkansas"
    | "California"
    | "Colorado"
    | "Connecticut"
    | "Delaware"
    | "Florida"
    | "Georgia"
    | "Hawaii"
    | "Idaho"
    | "Illinois"
    | "Indiana"
    | "Iowa"
    | "Kansas"
    | "Kentucky"
    | "Louisiana"
    | "Maine"
    | "Maryland"
    | "Massachusetts"
    | "Michigan"
    | "Minnesota"
    | "Mississippi"
    | "Missouri"
    | "Montana"
    | "Nebraska"
    | "Nevada"
    | "New Hampshire"
    | "New Jersey"
    | "New Mexico"
    | "New York"
    | "North Carolina"
    | "North Dakota"
    | "Ohio"
    | "Oklahoma"
    | "Oregon"
    | "Pennsylvania"
    | "Rhode Island"
    | "South Carolina"
    | "South Dakota"
    | "Tennessee"
    | "Texas"
    | "Utah"
    | "Vermont"
    | "Virginia"
    | "Washington"
    | "West Virginia"
    | "Wisconsin"
    | "Wyoming";
  zip?: string;
  county?: string;
  geo?: Geopoint;
  officePhone?: string;
  tollFreePhone?: string;
  officeFax?: string;
  officeEmail?: string;
  emergency24_7?: boolean;
  emergencyPhone?: string;
  appointmentRequired?: "Walk-Ins Welcome" | "Appointment Required";
  displayOnWebsite?: boolean;
  gbpCidUrl?: string;
  gbpPrimaryCategory?: string;
  gbpSecondaryCategories?: string;
  hours?: {
    mondayStatus?: "Open" | "Closed";
    mondayOpen?: string;
    mondayClose?: string;
    tuesdayStatus?: "Open" | "Closed";
    tuesdayOpen?: string;
    tuesdayClose?: string;
    wednesdayStatus?: "Open" | "Closed";
    wednesdayOpen?: string;
    wednesdayClose?: string;
    thursdayStatus?: "Open" | "Closed";
    thursdayOpen?: string;
    thursdayClose?: string;
    fridayStatus?: "Open" | "Closed";
    fridayOpen?: string;
    fridayClose?: string;
    saturdayStatus?: "Open" | "Closed";
    saturdayOpen?: string;
    saturdayClose?: string;
    sundayStatus?: "Open" | "Closed";
    sundayOpen?: string;
    sundayClose?: string;
  };
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height?: number;
  width?: number;
  aspectRatio?: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  thumbHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type AllSanitySchemaTypes =
  | PullQuote
  | Proof
  | VideoReference
  | Media
  | SanityImageAssetReference
  | MediaImage
  | BlockProse
  | SiloNavBlock
  | AttorneyPageReference
  | AttorneyHighlightBlock
  | CaseResultReference
  | CaseResultsBlock
  | PracticeAreaReference
  | NarrativeBlock
  | DifferentiatorBlock
  | BadgeReference
  | BadgesBlock
  | ReviewsSectionInline
  | ContentSectionInline
  | VideoSectionInline
  | TestimonialReference
  | FeaturedTestimonialInline
  | TestimonialsGridInline
  | BadgesSectionInline
  | CaseResultsSectionInline
  | AttorneySectionInline
  | PracticeAreaNavInline
  | SidebarTableOfContents
  | CtaFormSection
  | GeoPracticeAreaReference
  | ServiceAreaPageReference
  | PracticeAreaNavItem
  | HomeHeroDesign
  | HomeHeroContent
  | InternalHero
  | CtaButton
  | OfficeHours
  | ContentToken
  | BlockContent
  | SiteFormReference
  | SidebarFormEmbed
  | SidebarCtaBox
  | SidebarAttorneyList
  | GeneralPageReference
  | AboutPageReference
  | ContactPageReference
  | FaqPageReference
  | LocationPageReference
  | LandingPageReference
  | ReviewPageReference
  | BlogPostReference
  | SidebarNav
  | TestimonialsGridReference
  | FeaturedTestimonialReference
  | CtaSectionReference
  | ContentSectionReference
  | CaseResultsSectionReference
  | FaqSectionReference
  | BadgesSectionReference
  | AttorneySectionReference
  | ReviewsSectionReference
  | VideoSectionReference
  | VideoIndex
  | SanityImageCrop
  | SanityImageHotspot
  | Slug
  | ContentSection
  | CaseResultsSection
  | PracticeAreaNav
  | VideoSection
  | ReviewsSection
  | AttorneySection
  | BadgesSection
  | FaqItemReference
  | FaqSection
  | CtaSection
  | FeaturedTestimonial
  | TestimonialsGrid
  | Badge
  | PressItem
  | CaseResult
  | FaqItem
  | TestimonialsPage
  | Testimonial
  | HeroSettings
  | FooterSettings
  | MainNavigation
  | GlobalCta
  | EventIndex
  | EventCategoryReference
  | EventPage
  | EventCategory
  | ReviewPage
  | LandingPage
  | StaffPageReference
  | StaffIndex
  | StaffPage
  | AttorneyIndex
  | AttorneyPage
  | LocationReference
  | SidebarNavReference
  | SidebarAttorneyListReference
  | SidebarCtaBoxReference
  | SidebarFormEmbedReference
  | LocationPage
  | BlogTag
  | BlogCategoryReference
  | BlogTagReference
  | BlogPost
  | BlogCategory
  | BlogIndex
  | FaqPage
  | ContactPage
  | SiteForm
  | ServiceAreaIndex
  | ServiceAreaPage
  | GeoPracticeArea
  | GeneralPage
  | PracticeAreaNavReference
  | AboutPage
  | HomePage
  | PracticeArea
  | Video
  | SanityFileAssetReference
  | DesignSettings
  | SiteSettings
  | Location
  | Geopoint
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset;
